using System;
using System.Collections.Generic;
using System.Globalization;

namespace HardwareStore.Gameplay.Localization
{
    public sealed class RussianLocalizationCatalog : ILocalizationCatalog
    {
        private static readonly LocalizationEntry[] CatalogEntries =
        {
            E(LocalizationKey.ProductCementBagName, "Цемент 25 кг"),
            E(LocalizationKey.ProductBoardBundleName, "Пачка досок"),
            E(LocalizationKey.ProductPieceUnit, "шт."),

            E(LocalizationKey.ProjectCementFoundationTitle, "Стяжка в мастерской"),
            E(LocalizationKey.ProjectCementFoundationRequest,
                "Нужно подготовить материал для небольшой стяжки. " +
                "Предложите подходящий запас."),
            E(LocalizationKey.ProjectCementFoundationOffer0Title, "Эконом"),
            E(LocalizationKey.ProjectCementFoundationOffer0Description,
                "Минимальный объём без запаса."),
            E(LocalizationKey.ProjectCementFoundationOffer1Title, "Стандарт"),
            E(LocalizationKey.ProjectCementFoundationOffer1Description,
                "Рекомендуемый объём с небольшим запасом."),
            E(LocalizationKey.ProjectCementFoundationOffer2Title, "Профи"),
            E(LocalizationKey.ProjectCementFoundationOffer2Description,
                "Максимальный запас на исправление ошибок."),
            E(LocalizationKey.ProjectLumberShelvingTitle, "Полки для мастерской"),
            E(LocalizationKey.ProjectLumberShelvingRequest,
                "Нужно собрать рабочие полки. Предложите объём с подходящим запасом."),
            E(LocalizationKey.ProjectLumberShelvingOffer0Title, "Эконом"),
            E(LocalizationKey.ProjectLumberShelvingOffer0Description,
                "Минимальный объём без запаса."),
            E(LocalizationKey.ProjectLumberShelvingOffer1Title, "Стандарт"),
            E(LocalizationKey.ProjectLumberShelvingOffer1Description,
                "Рекомендуемый объём с небольшим запасом."),
            E(LocalizationKey.ProjectLumberShelvingOffer2Title, "Профи"),
            E(LocalizationKey.ProjectLumberShelvingOffer2Description,
                "Максимальный запас на исправление ошибок."),
            E(LocalizationKey.ProjectWorkbenchFoundationTitle, "Основание для верстака"),
            E(LocalizationKey.ProjectWorkbenchFoundationRequest,
                "Нужны цемент для основания и доски для рабочей поверхности. " +
                "Предложите баланс скорости, прочности и запаса."),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer0Title, "Быстрый старт"),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer0Description,
                "Минимум материалов и две ходки до машины."),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer1Title, "Крепкое основание"),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer1Description,
                "Больше цемента при умеренной себестоимости комплекта."),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer2Title, "Запас по дереву"),
            E(LocalizationKey.ProjectWorkbenchFoundationOffer2Description,
                "Больше досок и выше прибыль при максимальной загрузке машины."),

            E(LocalizationKey.HudStoreTitle, "СТРОЙБАЗА • ПРОТОТИП"),
            E(LocalizationKey.HudOrderLineStatus,
                "{0}: склад {1} • загружено {2} • нужно {3} {4}", 5),
            E(LocalizationKey.HudStockAndBalance,
                "На складе всего: {0} • баланс: {1:N0} ₽", 2),
            E(LocalizationKey.HudBalance, "Баланс: {0:N0} ₽", 1),
            E(LocalizationKey.HudControls,
                "WASD — идти   Shift — бег   E — действие   G — бросить   Esc — курсор"),
            E(LocalizationKey.HudControlsCarrying,
                "WASD — идти   Shift — бег   E — действие   G — бросить   " +
                "Esc — курсор  •  В руках: {0}", 1),
            E(LocalizationKey.HudConsultationTitle, "КОНСУЛЬТАЦИЯ КЛИЕНТА"),
            E(LocalizationKey.HudConsultationCapacity, "Вместимость машины: {0} ед.", 1),
            E(LocalizationKey.HudConsultationOfferHeader, "ВАРИАНТ {0} • {1}", 2),
            E(LocalizationKey.HudMaterialsHeader, "Материалы:"),
            E(LocalizationKey.HudMaterialLine,
                "{0}: склад {1} / нужно {2} {3}", 4),
            E(LocalizationKey.HudCargoSlots, "Мест в машине: {0}/{1}", 2),
            E(LocalizationKey.HudProductCost, "Себестоимость: {0:N0} ₽", 1),
            E(LocalizationKey.HudRevenue, "Выручка: {0:N0} ₽", 1),
            E(LocalizationKey.HudProfit, "Прибыль: {0:N0} ₽", 1),
            E(LocalizationKey.HudSelected, "ВЫБРАНО"),
            E(LocalizationKey.HudConsultationControls,
                "← — предыдущее   → — следующее   Enter — подтвердить   Esc — закрыть"),
            E(LocalizationKey.HudProcurementTitle, "ЗАКУПКИ"),
            E(LocalizationKey.HudProcurementOrderTitle, "Заказ клиента • {0}", 1),
            E(LocalizationKey.HudProcurementBalanceStorage,
                "Баланс: {0:N0} ₽   •   Свободных мест на складе: {1}", 2),
            E(LocalizationKey.HudProcurementProductDetails,
                "Поставка: {0} {1}\nСтоимость: {2:N0} ₽\nОстаток денег: {3:N0} ₽\n\n" +
                "В заказе осталось: {4} {1}\nНа складе: {5} {1}\n" +
                "Дефицит по строке: {6} {1}", 7),
            E(LocalizationKey.HudProcurementControls,
                "← — предыдущее   → — следующее   Enter — купить   Esc — закрыть"),
            E(LocalizationKey.HudCursorHint,
                "Курсор свободен • нажмите Esc, чтобы продолжить"),
            E(LocalizationKey.HudObjectiveDelivery,
                "Принять поставку • {0}: {1}/{2} {3}", 4),
            E(LocalizationKey.HudObjectiveNoCustomer, "Ожидаем следующего клиента"),
            E(LocalizationKey.HudObjectiveArriving,
                "Клиент прибывает и направляется к стойке"),
            E(LocalizationKey.HudObjectiveConsulting,
                "Обсудить проект с клиентом у стойки"),
            E(LocalizationKey.HudObjectiveWaitingForStock,
                "Подготовить заказ • доступно {0}/{1} ед.", 2),
            E(LocalizationKey.HudObjectiveWaitingReady, "Принять заказ • {0} ед.", 1),
            E(LocalizationKey.HudObjectiveLoading, "Отгрузить заказ • {0}/{1} ед.", 2),
            E(LocalizationKey.HudObjectiveCompleted, "Заказ выполнен • автомобиль загружен"),
            E(LocalizationKey.HudObjectiveReturning, "Клиент возвращается к машине"),
            E(LocalizationKey.HudObjectiveDeparting, "Машина клиента уезжает"),
            E(LocalizationKey.HudStockNoCustomer, "Товаров на складе: {0}", 1),
            E(LocalizationKey.HudStockProject, "Проект клиента • {0}", 1),
            E(LocalizationKey.HudStockOrder,
                "Позиций в заказе: {0} • товаров на складе: {1}", 2),
            E(LocalizationKey.ProcurementStatusNotRequired,
                "Не требуется для текущего заказа"),
            E(LocalizationKey.ProcurementStatusStockSufficient,
                "Запаса для заказа достаточно"),
            E(LocalizationKey.ProcurementStatusInsufficientStorage,
                "Недостаточно места: свободно {0}/{1}", 2),
            E(LocalizationKey.ProcurementStatusInsufficientMoney,
                "Недостаточно денег: нужно {0:N0} ₽", 1),
            E(LocalizationKey.ProcurementStatusAvailable, "Можно заказать"),

            E(LocalizationKey.PromptInboundOnlyAtIntake,
                "На приёмку можно положить только товар из поставки"),
            E(LocalizationKey.PromptStorageFull, "На складе нет свободного места"),
            E(LocalizationKey.PromptStoreInboundProduct,
                "E — принять на склад • товар: {0}", 1),
            E(LocalizationKey.PromptNoActiveOrderCarrying,
                "Нет активного заказа • в руках: {0} • G — бросить", 1),
            E(LocalizationKey.PromptArrivingCarrying,
                "Клиент прибывает и направляется к стойке • в руках: {0} • G — бросить", 1),
            E(LocalizationKey.PromptCompletedCarrying,
                "Заказ завершён • в руках: {0} • G — бросить", 1),
            E(LocalizationKey.PromptConsultFirstCarrying,
                "Сначала согласуйте предложение • в руках: {0} • G — бросить", 1),
            E(LocalizationKey.PromptAcceptOrderFirst, "Сначала примите заказ у стойки"),
            E(LocalizationKey.PromptCarryToCustomerVehicle,
                "Отнесите товар в машину клиента • товар: {0}", 1),
            E(LocalizationKey.PromptProductNotInOrderCarrying,
                "Товар не входит в заказ: {0} • G — бросить", 1),
            E(LocalizationKey.PromptOrderLineAlreadyLoadedCarrying,
                "Позиция уже загружена: {0} • G — бросить", 1),
            E(LocalizationKey.PromptFreeHandsForProcurement,
                "Освободите руки, чтобы открыть каталог закупок"),
            E(LocalizationKey.PromptDeliveryBeingStocked,
                "Поставка принимается • товар: {0} • принято: {1}/{2} {3}", 4),
            E(LocalizationKey.PromptWaitForCustomer,
                "Ожидайте клиента — поставка выбирается под заказ"),
            E(LocalizationKey.PromptOrderCompletedWait,
                "Заказ выполнен — дождитесь следующего клиента"),
            E(LocalizationKey.PromptArrivingWaitForConsultation,
                "Клиент прибывает — дождитесь начала консультации"),
            E(LocalizationKey.PromptConsultAtCounterFirst,
                "Сначала согласуйте предложение с клиентом у стойки"),
            E(LocalizationKey.PromptStockSufficient,
                "Запаса для текущего заказа достаточно"),
            E(LocalizationKey.PromptOpenProcurement, "E — открыть каталог закупок"),
            E(LocalizationKey.PromptBringDeliveryToIntake,
                "Принесите товар из поставки на приёмку • товар: {0}", 1),
            E(LocalizationKey.PromptStorageCountWaitCustomer,
                "Товаров на складе: {0} • Ожидайте следующего клиента", 1),
            E(LocalizationKey.PromptStorageEmptyOrderDelivery,
                "Склад пуст — можно заказать поставку"),
            E(LocalizationKey.PromptArrivingPrepareProduct,
                "Клиент прибывает и направляется к стойке — можно подготовить товар"),
            E(LocalizationKey.PromptCustomerReturningWait,
                "Клиент возвращается к машине — ожидайте следующего"),
            E(LocalizationKey.PromptCustomerVehicleDepartingWait,
                "Машина клиента уезжает — ожидайте следующего"),
            E(LocalizationKey.PromptConsultProjectFirst,
                "Сначала согласуйте предложение • проект: {0}", 1),
            E(LocalizationKey.PromptAllLinesLoaded,
                "Все позиции загружены — заказ завершается"),
            E(LocalizationKey.PromptFocusStockProduct,
                "Наведитесь на товар: {0} • E — взять", 1),
            E(LocalizationKey.PromptNoStockForOrder,
                "Нет товара для заказа: {0} • закажите поставку", 1),
            E(LocalizationKey.PromptAllLinesReadyAcceptOrder,
                "Все позиции готовы • примите заказ у стойки"),
            E(LocalizationKey.PromptNeedProductDelivery,
                "Нужен товар: {0} • доступно: {1}/{2} {3} • закажите поставку", 4),
            E(LocalizationKey.PromptCompletedStockCount,
                "Заказ выполнен • товаров на складе: {0}", 1),
            E(LocalizationKey.PromptCompletedStorageEmpty,
                "Заказ выполнен • склад пуст"),
            E(LocalizationKey.PromptLoadedProduct,
                "Товар уже загружен клиенту • товар: {0}", 1),
            E(LocalizationKey.PromptHandsOccupied, "Руки заняты • G — бросить предмет"),
            E(LocalizationKey.PromptPickInboundProduct,
                "E — взять из поставки • товар: {0}", 1),
            E(LocalizationKey.PromptProductUnavailable, "Этот товар сейчас нельзя взять"),
            E(LocalizationKey.PromptNoCustomerProductNotRequired,
                "Ожидайте следующего клиента — товар пока не требуется"),
            E(LocalizationKey.PromptArrivingProductWait,
                "Клиент прибывает и направляется к стойке — дождитесь консультации"),
            E(LocalizationKey.PromptConsultFirst,
                "Сначала согласуйте предложение с клиентом у стойки"),
            E(LocalizationKey.PromptOrderAlreadyCompleted, "Заказ уже выполнен"),
            E(LocalizationKey.PromptPickStockProduct,
                "E — взять со склада • товар: {0}", 1),
            E(LocalizationKey.PromptProductNotInOrder,
                "Товар не входит в заказ: {0}", 1),
            E(LocalizationKey.PromptOrderLineAlreadyLoaded,
                "Позиция уже загружена полностью: {0}", 1),
            E(LocalizationKey.PromptCounterWaitCustomer, "Ожидаем следующего клиента"),
            E(LocalizationKey.PromptCounterCustomerApproaching, "Клиент направляется к стойке"),
            E(LocalizationKey.PromptCounterVehicleDeparting, "Машина клиента уезжает"),
            E(LocalizationKey.PromptCounterCustomerReturning, "Клиент возвращается к машине"),
            E(LocalizationKey.PromptFreeHandsForConsultation,
                "Освободите руки перед консультацией"),
            E(LocalizationKey.PromptDiscussProject, "E — обсудить проект • {0}", 1),
            E(LocalizationKey.PromptAcceptOrder,
                "E — принять заказ • {0} поз. • {1} ед.", 2),
            E(LocalizationKey.PromptMissingProduct,
                "Не хватает: {0} • склад {1}/нужно {2} {3}", 4),
            E(LocalizationKey.PromptOrderAcceptedLoadVehicle,
                "Заказ принят — загрузите товар в машину клиента"),
            E(LocalizationKey.PromptOrderCompletedCustomerLeaving,
                "Заказ выполнен — клиент готовится уезжать"),
            E(LocalizationKey.PromptLoadingWaitConsultation,
                "Клиент прибывает и направляется к стойке — дождитесь консультации"),
            E(LocalizationKey.PromptLoadingCompletedVehicleDeparting,
                "Машина клиента уезжает — загрузка завершена"),
            E(LocalizationKey.PromptLoadingCompletedCustomerReturning,
                "Клиент возвращается к машине — загрузка завершена"),
            E(LocalizationKey.PromptLoadingConsultFirst,
                "Сначала согласуйте предложение с клиентом у стойки"),
            E(LocalizationKey.PromptLoadingAcceptOrderFirst,
                "Сначала примите заказ у стойки"),
            E(LocalizationKey.PromptLoadingVehicleFull,
                "Машина загружена — заказ выполнен"),
            E(LocalizationKey.PromptLoadingAllLinesLoaded,
                "Все позиции загружены — заказ завершается"),
            E(LocalizationKey.PromptBringProductFromStorage,
                "Принесите со склада: {0} • загружено {1}/{2}", 3),
            E(LocalizationKey.PromptLoadingProductNotInOrder,
                "Товар не входит в заказ: {0}", 1),
            E(LocalizationKey.PromptLoadingLineAlreadyLoaded,
                "Позиция уже загружена: {0}", 1),
            E(LocalizationKey.PromptProductMustComeFromStorage,
                "Товар нужно взять со склада: {0}", 1),
            E(LocalizationKey.PromptCustomerVehicleNoSpace,
                "В машине клиента нет свободного места"),
            E(LocalizationKey.PromptLoadProduct,
                "E — загрузить • {0} • {1}/{2}", 3),

            E(LocalizationKey.NotificationAcceptCurrentDeliveryFirst,
                "Сначала примите текущую поставку на склад"),
            E(LocalizationKey.NotificationWaitForCustomer,
                "Дождитесь клиента, чтобы выбрать поставку под его заказ"),
            E(LocalizationKey.NotificationOrderCompletedWaitCustomer,
                "Текущий заказ уже выполнен — дождитесь следующего клиента"),
            E(LocalizationKey.NotificationWaitForCustomerConsultation,
                "Дождитесь клиента, чтобы согласовать предложение"),
            E(LocalizationKey.NotificationConsultAtCounterFirst,
                "Сначала согласуйте предложение с клиентом у стойки"),
            E(LocalizationKey.NotificationCurrentOrderNeedsOneProduct,
                "Для текущего заказа нужен товар: {0}", 1),
            E(LocalizationKey.NotificationCurrentOrderNeedsTwoProducts,
                "Для текущего заказа нужны: {0}, {1}", 2),
            E(LocalizationKey.NotificationProductStockSufficient,
                "Товара уже достаточно: {0} • доступно {1}/{2}", 3),
            E(LocalizationKey.NotificationStorageSpaceInsufficient,
                "Недостаточно места на складе: свободно {0}/{1}", 2),
            E(LocalizationKey.NotificationMoneyInsufficient,
                "Недостаточно денег на поставку: нужно {0:N0} ₽", 1),
            E(LocalizationKey.NotificationDeliveryOrdered,
                "Поставка заказана • товар: {0} • количество: {1} {2} • −{3:N0} ₽", 4),
            E(LocalizationKey.NotificationProductLoaded,
                "Товар загружен • {0}: {1}/{2} {3}", 4),
            E(LocalizationKey.NotificationOfferConfirmed,
                "Предложение сформировано • {0} • объём: {1} • сумма: {2:N0} ₽", 3),
            E(LocalizationKey.NotificationDeliveryCompleted,
                "Поставка полностью принята на склад"),
            E(LocalizationKey.NotificationOrderStockMissingOne,
                "Недостаточно товара на складе: {0} {1}/{2}", 3),
            E(LocalizationKey.NotificationOrderStockMissingTwo,
                "Недостаточно товара на складе: {0} {1}/{2} • {3} {4}/{5}", 6),
            E(LocalizationKey.NotificationOrderAccepted,
                "Заказ принят • позиций: {0} • товаров: {1}", 2),
            E(LocalizationKey.NotificationProductStocked,
                "Принято на склад: {0}/{1}", 2),
            E(LocalizationKey.NotificationStorageFull, "На складе нет свободного места"),
            E(LocalizationKey.NotificationOrderCompleted,
                "Заказ выполнен: +{0:N0} ₽", 1),
            E(LocalizationKey.NotificationFreeHandsForProcurement,
                "Освободите руки, чтобы открыть закупки"),
            E(LocalizationKey.NotificationProcurementNotRequired,
                "Для текущего заказа закупка не требуется"),

            E(LocalizationKey.WorldOrderCounter, "ЗАКАЗ КЛИЕНТА"),
            E(LocalizationKey.WorldProcurement, "ЗАКУПКИ"),
            E(LocalizationKey.WorldStorageCatalog,
                "СКЛАД • ЦЕМЕНТ 25 КГ • ПАЧКА ДОСОК"),
            E(LocalizationKey.WorldStorageIntake, "ПРИЁМКА"),
            E(LocalizationKey.WorldCustomerLoadingBay, "ПОГРУЗКА КЛИЕНТА"),
            E(LocalizationKey.WorldDeliveryIntake, "ПРИЁМКА ПОСТАВКИ"),
            E(LocalizationKey.WorldCustomerVehicleLoading, "ЗАГРУЗИТЬ"),
            E(LocalizationKey.WorldBoardProductLabel,
                "B-01 • ПАЧКА ДОСОК • {0:N0} ₽/ШТ.", 1)
        };

        private static readonly IReadOnlyList<LocalizationEntry> ReadOnlyEntries =
            Array.AsReadOnly(CatalogEntries);

        public LanguageId Language => LanguageId.Russian;
        public CultureInfo Culture => CultureInfo.GetCultureInfo("ru-RU");
        public IReadOnlyList<LocalizationEntry> Entries => ReadOnlyEntries;

        private static LocalizationEntry E(
            LocalizationKey key,
            string template,
            int argumentCount = 0) =>
            new(key, template, argumentCount);
    }
}
